### PR TITLE
Add Critical Severity

### PR DESCRIPTION
**Pull request by zpriddy**
This adds a 4th severity of Critical. This is very helpful if you want to trigger pages off of only Critical Alerts or Cases

This does change the color of items so there may want to be some talk around it

### CODE REVIEW

**Comment by zpriddy** [comment]
Screen Shot 2019-03-14 at 11 57 13 PM

**Comment by zpriddy** [comment]
This may actually start to cover #11

**Comment by crackytsi** [comment]
@zpriddy Hi, Thanks for adding so many interesting PRs. Unforunately it seems that your PRs aren't seperated, so the new status and critical severity are combined.
Are you able to split that?

**Comment by zpriddy** [comment]
Yeah I noticed that. I can split those out.

**Comment by zpriddy** [comment]
Replacing with #939

**Pull request closed without merging**
